services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=carRental
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default


  carRental:
    image: car-rental
    container_name: carRental
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - default

networks:
  default:
    name: carRental

volumes:
  mysql_data: