spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/carRental}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
#    jpa:
#      database-platform: org.hibernate.dialect.H2Dialect
#      hibernate:
#        ddl-auto: update
#      show-sql: false
#      properties:
#        hibernate:
#          dialect:
#          format-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: car-rental
    server: http://localhost:${server.port}
    title: carRental
    version: 1.0.1

jwt:
  secretKey: abc@123

app:
  upload:
    dir: ./uploads
  python:
    ocr:
      url: http://localhost:8081/ocr/service